# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasisPreticalTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasisPreticalTask

pod 'IQKeyboardManager', '~> 6.5.9'
pod 'SVPinView'  

end
